name: Update YouTube Videos

on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9 AM UTC
  workflow_dispatch:     # Allow manual trigger

permissions:
  contents: write  # Explicitly allow write permissions to the repository

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios

      - name: Run Update Script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: node scripts/updateVideos.js

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}  # Ensure you have this token set in the secrets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add videos.json
          git commit -m "Auto-update videos.json" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PUSH_TOKEN }}@github.com/${{ github.repository }}
          git push
